# Generated by Django 6.0 on 2026-01-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customusermodel',
            managers=[
            ],
        ),
    ]
